# Generated by Django 2.1.7 on 2019-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('cover', models.URLField()),
                ('release_date', models.DateField(blank=True)),
                ('duration', models.IntegerField()),
                ('director', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
