# Generated by Django 2.1.7 on 2019-03-17 19:06

from django.db import migrations, models


def change_duplicate_titles(apps, schema_editor):
    Movie = apps.get_model('movies_api', 'Movie')

    # find duplicate movies
    movie_count_list = Movie.objects.values('title').annotate(count=models.Count('title'))

    for duplicated_title in filter(lambda item: item['count'] > 1, movie_count_list):
        for i, movie in enumerate(Movie.objects.filter(title=duplicated_title['title'])):
            movie.title = f'{movie.title} ({i+1})'
            movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_auto_20190316_1803'),
    ]

    operations = [
        migrations.RunPython(change_duplicate_titles, lambda apps, schema_editor: None),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
